search:
  safe_search: 0
  formats: [html, json]
  autocomplete: ""
  default_lang: "zh-CN"
server:
  bind_address: "127.0.0.1"
  port: 8899
  limiter: false
  public_instance: false
  method: "GET"
  secret_key: "ant-colony-searxng-secret-2026"
  image_proxy: false
outgoing:
  request_timeout: 4.0
  max_request_timeout: 6.0
ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: auto
doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'
default_doi_resolver: 'oadoi.org'
engines:
  - name: github
    engine: github
    shortcut: gh
    timeout: 4.0
  - name: brave
    engine: brave
    shortcut: br
    timeout: 4.0
    disabled: false
  - name: qwant
    engine: qwant
    shortcut: qw
    timeout: 4.0
    disabled: false
  - name: startpage
    engine: startpage
    shortcut: sp
    timeout: 4.0
    disabled: false
  - name: bing
    engine: bing
    shortcut: bi
    timeout: 4.0
    disabled: true
  - name: yahoo
    engine: yahoo
    shortcut: yh
    timeout: 4.0
    disabled: false
