"""Ant Colony — enterprise multi-agent collaboration system bootstrap.

Run this script to set up a clean deployment. It will:
1. Check prerequisites (Python 3.12+, pip)
2. Install Python dependencies
3. Prompt for platform credentials (WeCom / Feishu / DingTalk)
4. Create environment config files
5. Download AI role files from agency-agents-zh
6. Initialize databases
7. Print next steps for starting services
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
INFRA_DIR = PROJECT_ROOT / "infra"

ENV_FILE = INFRA_DIR / ".env.wecom"

PACKAGES = [
    "PyMuPDF",       # PDF processing & OCR
    "python-docx",   # Word document processing
    "python-pptx",   # PowerPoint processing
    "openpyxl",      # Excel processing
    "httpx",         # HTTP client (for LLM API)
]

OPTIONAL_PACKAGES = [
    ("marker-pdf", "Advanced OCR (requires ~5GB for models)"),
    ("dingtalk-stream", "DingTalk stream mode SDK"),
    ("lark-oapi", "Feishu SDK (optional, uses stdlib otherwise)"),
    ("python-telegram-bot", "Telegram Bot SDK (optional, uses polling otherwise)"),
]


def bold(text: str) -> str:
    return f"\033[1m{text}\033[0m"


def prompt(text: str, default: str = "") -> str:
    if default:
        prompt_text = f"{text} [{default}]: "
    else:
        prompt_text = f"{text}: "
    try:
        value = input(prompt_text).strip()
        return value if value else default
    except (EOFError, KeyboardInterrupt):
        return default


def prompt_password(text: str) -> str:
    """Simple password prompt (no echo hiding in basic terminals)."""
    print(f"{text}: ", end="", flush=True)
    try:
        value = input().strip()
        return value
    except (EOFError, KeyboardInterrupt):
        return ""


def check_python() -> bool:
    print(f"\n{bold('Checking Python version...')}")
    v = sys.version_info
    if v.major < 3 or (v.major == 3 and v.minor < 10):
        print(f"  Python 3.10+ required (found {v.major}.{v.minor})")
        return False
    print(f"  Python {v.major}.{v.minor}.{v.micro} - OK")
    return True


def install_packages() -> bool:
    print(f"\n{bold('Installing core packages...')}")
    for pkg in PACKAGES:
        print(f"  Installing {pkg}...", end=" ", flush=True)
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", pkg, "--quiet"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print("OK")
        else:
            print(f"FAILED: {result.stderr[:80]}")
    print(f"\n{bold('Optional packages (install when needed):')}")
    for pkg, desc in OPTIONAL_PACKAGES:
        print(f"  pip install {pkg}  # {desc}")
    return True


def configure_wecom() -> dict[str, str]:
    """Configure WeCom credentials."""
    print(f"\n{bold('=== 企业微信 (WeCom) Configuration ===')}")
    print("Leave blank and press Enter to skip WeCom setup.\n")

    config = {}
    config["WECOM_CORP_ID"] = prompt("企业微信 CorpID", "")
    if not config["WECOM_CORP_ID"]:
        return {}

    config["WECOM_AGENT_ID"] = prompt("AgentId", "1000006")
    config["WECOM_SECRET"] = prompt_password("应用的 Secret")
    config["WECOM_CALLBACK_TOKEN"] = prompt("回调 Token (留空跳过回调配置)", "")
    config["WECOM_CALLBACK_AES_KEY"] = prompt("回调 EncodingAESKey", "")
    config["WECOM_CONTACT_SECRET"] = prompt("通讯录同步 Secret (留空跳过)", "")

    return {k: v for k, v in config.items() if v}


def configure_feishu() -> dict[str, str]:
    """Configure Feishu credentials."""
    print(f"\n{bold('=== 飞书 (Feishu) Configuration ===')}")
    print("Leave blank to skip.\n")

    config = {}
    config["FEISHU_APP_ID"] = prompt("App ID", "")
    if not config["FEISHU_APP_ID"]:
        return {}

    config["FEISHU_APP_SECRET"] = prompt_password("App Secret")
    config["FEISHU_DOMAIN"] = prompt("Domain (cn=中国, intl=国际)", "cn")

    return config


def configure_dingtalk() -> dict[str, str]:
    """Configure DingTalk credentials."""
    print(f"\n{bold('=== 钉钉 (DingTalk) Configuration ===')}")
    print("Leave blank to skip.\n")

    config = {}
    config["DINGTALK_CLIENT_ID"] = prompt("Client ID (AppKey)", "")
    if not config["DINGTALK_CLIENT_ID"]:
        return {}

    config["DINGTALK_CLIENT_SECRET"] = prompt_password("Client Secret (AppSecret)")

    return config


def write_env_file(config: dict[str, str]) -> None:
    """Write credentials to .env.wecom file."""
    INFRA_DIR.mkdir(parents=True, exist_ok=True)
    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write("# Ant Colony - Platform Credentials\n")
        f.write("# Generated by bootstrap.py on " +
                 __import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "\n\n")
        for key, value in sorted(config.items()):
            f.write(f"{key}={value}\n")
    os.chmod(ENV_FILE, 0o600)  # Read/write for owner only
    print(f"\n  Credentials saved to {ENV_FILE} (permissions: 600)")


def setup_data_dirs() -> None:
    """Create required data directories."""
    dirs = [
        DATA_DIR,
        DATA_DIR / "memory",
        DATA_DIR / "files",
        DATA_DIR / "backups",
        DATA_DIR / "cloud_sync",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        print(f"  Created {d.relative_to(PROJECT_ROOT)}/")
    print("")

    # Ask about role files
    print(f"{bold('AI Expert Roles')}")
    download = prompt("Download 215 AI expert roles from agency-agents-zh? (y/n)", "y")
    if download.lower() in ("y", "yes", ""):
        roles_dir = DATA_DIR / "roles"
        roles_dir.mkdir(parents=True, exist_ok=True)
        print("  Downloading role files... (this may take a minute)")
        try:
            import urllib.request
            import json as _json

            url = "https://api.github.com/repos/jnMetaCode/agency-agents-zh/git/trees/main?recursive=1"
            base = "https://raw.githubusercontent.com/jnMetaCode/agency-agents-zh/main/"
            dir_cats = {"engineering", "design", "marketing", "product", "sales", "finance",
                        "hr", "legal", "supply-chain", "testing", "support", "specialized",
                        "paid-media", "project-management", "academic", "game-development",
                        "spatial-computing", "strategy", "integrations"}

            with urllib.request.urlopen(url, timeout=30) as resp:
                tree = _json.loads(resp.read())

            count = 0
            for item in tree.get("tree", []):
                if item["type"] == "blob" and item["path"].endswith(".md"):
                    cat = item["path"].split("/")[0]
                    if cat in dir_cats:
                        local_path = roles_dir / item["path"]
                        local_path.parent.mkdir(parents=True, exist_ok=True)
                        try:
                            urllib.request.urlretrieve(base + item["path"], local_path)
                            count += 1
                        except Exception:
                            pass
            print(f"  Downloaded {count} role files to data/roles/")
        except Exception as e:
            print(f"  Download failed: {e} (you can run this step later)")


def setup_systemd(env_file: str) -> None:
    """Print systemd service setup instructions."""
    print(f"\n{bold('Systemd Service Setup')}")
    print(f"  To use credentials with the gateway service, ensure:")
    print(f"  /etc/systemd/system/ant-colony-gateway.service has:")
    print(f"    EnvironmentFile={env_file}")


def print_next_steps() -> None:
    """Print post-installation instructions."""
    print(f"\n{bold('=== Next Steps ===')}")
    print(f"  1. Start the gateway:")
    print(f"     python {PROJECT_ROOT}/run_gateway.py")
    print(f"")
    print(f"  2. Or install systemd services:")
    print(f"     sudo cp infra/*.service /etc/systemd/system/")
    print(f"     sudo systemctl daemon-reload")
    print(f"     sudo systemctl start ant-colony-gateway")
    print(f"")
    print(f"  3. In the chat, add yourself as admin:")
    print(f"     添加管理员 [你的姓名]")
    print(f"")
    print(f"  4. Add more admins (when you are one):")
    print(f"     添加管理员 [姓名]")
    print(f"")
    print(f"  5. For full deployment, also start:")
    print(f"     - gbrain-bridge (PostgreSQL knowledge graph)")
    print(f"     - hindsight-bridge (vector memory)")
    print(f"     - embed-service (semantic embeddings)")
    print(f"  See AGENTS.md for details.")
    print(f"")

    # Show registered tools summary
    try:
        sys.path.insert(0, str(PROJECT_ROOT))
        from src.tools.builtin import BUILTIN_TOOLS
        print(f"{bold('=== Registered Tools ({} total) ===')}".format(len(BUILTIN_TOOLS)))
        categories = {}
        for t in BUILTIN_TOOLS:
            cat = t.category if hasattr(t, 'category') else 'other'
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(t.name)
        for cat, tools in sorted(categories.items()):
            print(f"  {cat}: {', '.join(t for t in tools[:6])}{'...' if len(tools) > 6 else ''}")
        print(f"  Total: {len(BUILTIN_TOOLS)} tools")
    except Exception:
        pass


def main() -> None:
    print(f"\n{bold('Ant Colony — Enterprise Multi-Agent Collaboration')}")
    print(f"{bold('Bootstrap Installation')}")
    print("=" * 50)

    if not check_python():
        sys.exit(1)

    install_packages()

    # Platform configuration
    all_config = {}
    all_config.update(configure_wecom())
    all_config.update(configure_feishu())
    all_config.update(configure_dingtalk())

    if all_config:
        write_env_file(all_config)
    else:
        print(f"\n  {bold('No credentials configured.')} You can add them later to {ENV_FILE}.")

    setup_data_dirs()

    print(f"\n{bold('Initializing database...')}")
    try:
        sys.path.insert(0, str(PROJECT_ROOT))
        from src.store.database import Database
        db = Database.get(str(DATA_DIR / "ant-colony.db"))
        conn = db.connect()
        # Run migrations - import modules that create tables
        from src.knowledge.fts_repo import FtsKnowledgeRepository
        from src.knowledge.cloud_drive import _ensure_table
        from src.store.task_repo import TaskRepository
        _ensure_table()
        conn.close()
        print("  Database initialized")
    except Exception as e:
        print(f"  Database init: {e} (will initialize on first start)")

    setup_systemd(str(ENV_FILE) if ENV_FILE.exists() else "infra/.env.wecom")
    print_next_steps()

    print(f"\n{bold('Installation complete!')}")


if __name__ == "__main__":
    main()
